# SPDX-License-Identifier: MIT

"""V-014: structural-scale stress — wide, long, and deep diagrams.

The suite exercises numerically hard problems (V-008) and long horizons
(T-113 phase 4) but nothing structurally *large*: hundreds of blocks in one
diagram, deep subdiagram nesting, or very wide fan-in routing. These are the
shapes autogenerated / product-family models take, and they stress the
flattening pass, the port-cache plumbing, and XLA program size rather than
the solver. Each test has an analytically exact expected value, so a wrong
answer (not just a crash) is caught.

Empirical scaling on 2026-07-09 (CPU, arm64): a 200-block serial Gain chain
builds in ~0.05s and simulates in ~0.4s — so these stay in the fast tier.
"""

import numpy as np
import pytest

import jaxonomy
from jaxonomy.library import Adder, Constant, Gain, Integrator
from jaxonomy.library import Demux, Mux

pytestmark = pytest.mark.minimal


class TestLongSerialChain:
    @pytest.mark.parametrize("n_blocks", [64, 256])
    def test_gain_chain_exact_product(self, n_blocks):
        """Constant(1) -> Gain(1.01)^N -> Integrator over 1s = 1.01^N."""
        builder = jaxonomy.DiagramBuilder()
        src = builder.add(Constant(1.0))
        prev = src.output_ports[0]
        for k in range(n_blocks):
            g = builder.add(Gain(1.01, name=f"g{k}"))
            builder.connect(prev, g.input_ports[0])
            prev = g.output_ports[0]
        integ = builder.add(Integrator(initial_state=0.0))
        builder.connect(prev, integ.input_ports[0])
        diagram = builder.build()

        results = jaxonomy.simulate(
            diagram,
            diagram.create_context(),
            (0.0, 1.0),
            recorded_signals={"x": integ.output_ports[0]},
        )
        expected = 1.01**n_blocks
        assert float(results.outputs["x"][-1]) == pytest.approx(expected, rel=1e-6)


class TestDeepNesting:
    @staticmethod
    def _nested_gain(depth):
        """Build `depth` levels of subdiagrams, each wrapping one Gain(2.0)."""
        inner = None
        for level in range(depth):
            b = jaxonomy.DiagramBuilder()
            g = b.add(Gain(2.0, name=f"gain_L{level}"))
            head_in = g.input_ports[0]
            tail_out = g.output_ports[0]
            if inner is not None:
                child = b.add(inner)
                b.connect(g.output_ports[0], child.input_ports[0])
                tail_out = child.output_ports[0]
            b.export_input(head_in, name="u")
            b.export_output(tail_out, name="y")
            inner = b.build(name=f"level{level}")
        return inner

    @pytest.mark.parametrize("depth", [4, 8])
    def test_nested_subdiagrams_compose(self, depth):
        """Signal through `depth` nested Gain(2.0) wrappers = 2^depth."""
        nested = self._nested_gain(depth)

        builder = jaxonomy.DiagramBuilder()
        src = builder.add(Constant(3.0))
        wrapped = builder.add(nested)
        integ = builder.add(Integrator(initial_state=0.0))
        builder.connect(src.output_ports[0], wrapped.input_ports[0])
        builder.connect(wrapped.output_ports[0], integ.input_ports[0])
        diagram = builder.build()

        results = jaxonomy.simulate(
            diagram,
            diagram.create_context(),
            (0.0, 1.0),
            recorded_signals={"x": integ.output_ports[0]},
        )
        expected = 3.0 * (2.0**depth)
        assert float(results.outputs["x"][-1]) == pytest.approx(expected, rel=1e-6)


class TestWideRouting:
    @pytest.mark.parametrize("width", [32, 128])
    def test_wide_mux_demux_roundtrip(self, width):
        """width Constants -> Multiplexer -> DeMultiplexer -> Adder recovers
        the exact sum 0+1+...+(width-1)."""
        builder = jaxonomy.DiagramBuilder()
        mux = builder.add(Mux(width, name="mux"))
        for k in range(width):
            c = builder.add(Constant(float(k), name=f"c{k}"))
            builder.connect(c.output_ports[0], mux.input_ports[k])
        demux = builder.add(Demux(width, name="demux"))
        builder.connect(mux.output_ports[0], demux.input_ports[0])
        adder = builder.add(Adder(width, name="sum"))
        for k in range(width):
            builder.connect(demux.output_ports[k], adder.input_ports[k])
        diagram = builder.build()

        ctx = diagram.create_context()
        total = adder.output_ports[0].eval(ctx)
        expected = width * (width - 1) / 2.0
        assert float(total) == pytest.approx(expected)

    def test_wide_fan_out_single_source(self):
        """One source feeding 100 independent Gains — exercises the port
        cache under heavy fan-out. Sum of k*x for k=0..99 at x=2."""
        width = 100
        builder = jaxonomy.DiagramBuilder()
        src = builder.add(Constant(2.0))
        adder = builder.add(Adder(width, name="sum"))
        for k in range(width):
            g = builder.add(Gain(float(k), name=f"g{k}"))
            builder.connect(src.output_ports[0], g.input_ports[0])
            builder.connect(g.output_ports[0], adder.input_ports[k])
        diagram = builder.build()

        ctx = diagram.create_context()
        total = adder.output_ports[0].eval(ctx)
        expected = 2.0 * width * (width - 1) / 2.0
        assert float(total) == pytest.approx(expected)


class TestFanOutReconvergence:
    """Eager port evaluation must stay LINEAR in graph size when outputs
    fan out and reconverge — the natural shape of composed reference-
    submodel models.

    Before the per-eval-tree memo in framework/cache.py, each consumer
    re-evaluated its full upstream cone: a K-level diamond chain cost
    exactly 2^(K+2)-3 callback evaluations (K=18 → 1,048,573 calls, ~5 s;
    the DemoAeroRocketEngine app model never finished at all). With the
    memo it is O(K)."""

    def test_diamond_chain_eval_is_linear(self, monkeypatch):
        import jaxonomy.framework.cache as cache_mod

        depth = 18
        builder = jaxonomy.DiagramBuilder()
        src = builder.add(Constant(1.0))
        prev = src.output_ports[0]
        for k in range(depth):
            a = builder.add(Adder(2, name=f"a{k}"))
            builder.connect(prev, a.input_ports[0])
            builder.connect(prev, a.input_ports[1])
            prev = a.output_ports[0]
        diagram = builder.build()
        ctx = diagram.create_context()

        calls = {"n": 0}
        orig_calc = cache_mod.SystemCallback.calc

        def counted_calc(self, root_context):
            calls["n"] += 1
            return orig_calc(self, root_context)

        monkeypatch.setattr(cache_mod.SystemCallback, "calc", counted_calc)

        value = prev.eval(ctx)
        assert float(value) == 2.0**depth
        # Linear bound with headroom (a few callbacks per diamond level);
        # the pre-fix exponential behavior needed 2^(K+2)-3 ≈ 1e6 calls.
        assert calls["n"] < 20 * depth, (
            f"eager eval used {calls['n']} callback evaluations for a "
            f"{depth}-level diamond — exponential re-evaluation is back "
            "(framework/cache.py eval memo regression)."
        )


class TestManyIndependentStates:
    def test_100_parallel_integrators(self):
        """100 independent Integrators with distinct rates all integrate
        exactly — stresses the flattened state pytree, not the solver."""
        n = 100
        builder = jaxonomy.DiagramBuilder()
        integrators = []
        for k in range(n):
            c = builder.add(Constant(float(k + 1), name=f"c{k}"))
            integ = builder.add(Integrator(initial_state=0.0, name=f"i{k}"))
            builder.connect(c.output_ports[0], integ.input_ports[0])
            integrators.append(integ)
        diagram = builder.build()

        recorded = {f"x{k}": integrators[k].output_ports[0] for k in range(n)}
        results = jaxonomy.simulate(
            diagram, diagram.create_context(), (0.0, 2.0), recorded_signals=recorded
        )
        for k in range(n):
            assert float(results.outputs[f"x{k}"][-1]) == pytest.approx(
                2.0 * (k + 1), rel=1e-6
            ), f"integrator {k} drifted"
