# SPDX-License-Identifier: MIT

from __future__ import annotations

from dataclasses import dataclass, field
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from jaxonomy.framework.diagram import Diagram
    from jaxonomy.simulation.types import SimulatorOptions

__all__ = ["ValidationResult", "validate_diagram"]


@dataclass
class ValidationResult:
    valid: bool
    errors: list[str] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)

    def raise_if_invalid(self):
        if not self.valid:
            msg = "Diagram validation failed:\n" + "\n".join(
                f"  ERROR: {e}" for e in self.errors
            )
            raise ValueError(msg)

    def print_report(self):
        if self.errors:
            print("ERRORS:")
            for e in self.errors:
                print(f"  - {e}")
        if self.warnings:
            print("WARNINGS:")
            for w in self.warnings:
                print(f"  - {w}")
        if self.valid and not self.warnings:
            print("Diagram is valid.")


def validate_diagram(
    diagram,
    options=None,
) -> ValidationResult:
    """Check a diagram for common issues before simulation.

    Checks performed
    ----------------
    Warnings (do not block simulation):

    - ``CustomPythonBlock`` with ``enable_autodiff=True``: gradients through
      this block will be zero or incorrect; use ``CustomJaxBlock`` instead.
    - FMU block with ``enable_autodiff=True``: not differentiable.
    - ``max_major_steps=None`` with ``enable_autodiff=True``: heuristic
      estimate may be inaccurate; set it explicitly.

    Args:
        diagram: Root diagram to inspect.
        options: :class:`~jaxonomy.simulation.types.SimulatorOptions` used
            for context-sensitive checks (e.g. ``enable_autodiff``).

    Returns:
        :class:`ValidationResult` with ``errors`` and ``warnings`` lists.
        ``valid`` is ``True`` unless there are hard errors (none currently
        generated by this function — all checks produce warnings only).
    """
    errors: list[str] = []
    warnings_list: list[str] = []

    def walk(system, path: str = "") -> None:
        name = f"{path}.{system.name}" if path else system.name

        # --- CustomPythonBlock checks ---
        if _is_custom_python_block(system):
            if options and getattr(options, "enable_autodiff", False):
                warnings_list.append(
                    f"Block '{name}' is a CustomPythonBlock — not differentiable. "
                    "Gradients will be zero. Use CustomJaxBlock instead."
                )

        # --- FMU block checks ---
        if _is_fmu_block(system):
            if options and getattr(options, "enable_autodiff", False):
                warnings_list.append(
                    f"Block '{name}' is an FMU block — not differentiable."
                )

        # --- Recurse into sub-diagrams ---
        if hasattr(system, "nodes"):
            for subsystem in system.nodes:
                walk(subsystem, name)

    walk(diagram)

    # --- SimulatorOptions checks ---
    if options:
        if getattr(options, "enable_autodiff", False) and getattr(
            options, "max_major_steps", None
        ) is None:
            warnings_list.append(
                "max_major_steps not set with enable_autodiff=True. "
                "Using heuristic estimate which may be inaccurate; "
                "set max_major_steps explicitly."
            )

    return ValidationResult(
        valid=len(errors) == 0,
        errors=errors,
        warnings=warnings_list,
    )


def _is_custom_python_block(system) -> bool:
    """Return True if *system* is a ``CustomPythonBlock`` instance."""
    try:
        from jaxonomy.library.custom import CustomPythonBlock

        return isinstance(system, CustomPythonBlock)
    except ImportError:
        return False


def _is_fmu_block(system) -> bool:
    try:
        from jaxonomy.library.fmu_import import ModelicaFMU

        return isinstance(system, ModelicaFMU)
    except ImportError:
        return False
